name: Add or update publication manually 📝
description:  |
  Fill this form to add or update a publication on the website.
  
title: "[Add/update publication]"
labels: ["automatic-add-update-publication"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        If you choose to add a publication, fill out as many fields as possible. If you choose to update an existing publication, only fill out the required and the fields that you want to modify. Leave everything else blank.

        When updating an existing publication, the automated script will try to find a file at `_posts/papers/<year>-<month>-<day>-<shorthand>.md` and update that. Thus, make sure you are entering all 4 fields correctly.

        This form will automatically generate a PR that will be reviewed by the maintainers.

  - type: dropdown
    id: action
    attributes:
      label: Action
      description: What do you want to do?
      options:
        - "Add publication"
        - "Update publication"
    validations:
      required: true
  
  - type: input
    id: title
    attributes:
      label: Title
      description: The title of the paper
      placeholder: "Recursion is all you need"
    validations:
      required: true

  - type: input
    id: shorthand
    attributes:
      label: Shorthand
      description: |
        A shorthand of the paper's name, which will be used in the URL. For example, "<author>-<year>-<first word>", or its Arxiv ID or DOI code. 

        If you are updating an existing publication, this, along with the exact date, will be used to find the existing publication.
      placeholder: "1904.1234"
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author
      placeholder: "John Doe"
      description: What's the name of the first McGill-NLP affiliated author? We should be able to find their name in `_data/authors.yml`.
    validations:
      required: true

  - type: input
    id: names
    attributes:
      label: Names
      description: The names of all the authors, separated by commas.
      placeholder: "John Doe, John Doe Sr, Leland DeWitt"
    validations:
      required: true

  - type: input
    id: venue
    attributes:
      label: Venue
      description: A venue where the paper was published, or the name of the website (if it's a preprint).
      placeholder: "ACL 2022"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link
      description: The link to the paper.
      placeholder: "https://arxiv.org/abs/1901.01234"
    validations:
      required: true

  - type: input
    id: year
    attributes:
      label: Year
      description: The year the paper was published. Must be a four-digit number (or else the article might not show up).
      placeholder: "2022"
    validations:
      required: true

  - type: dropdown
    id: month
    attributes:
      label: Month
      description: The month the paper was published. If left blank, it will be set to `01`.
      multiple: false
      options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
    validations:
      required: false

  - type: dropdown
    id: day
    attributes:
      label: Day
      description: The day the paper was published. If left blank, it will be set to `01`.
      multiple: false
      options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Relevant tags, including the abbreviation of the venue name. Separate tags with commas.
      placeholder: "ACL, Recursion, Transformers"
    validations:
      required: false

  - type: input
    id: code
    attributes:
      label: Code
      description: Link to the code.
      placeholder: "https://github.com/McGill-NLP/project-name"
    validations:
      required: false

  - type: input
    id: webpage
    attributes:
      label: Webpage
      description: Link to the webpage.
      placeholder: "https://mcgill-nlp.github.io/project-name"
    validations:
      required: false

  - type: input
    id: video
    attributes:
      label: Video
      description: Link to the video.
      placeholder: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    validations:
      required: false

  - type: input
    id: twitter
    attributes:
      label: Twitter
      description: Link to the Twitter thread or account.
      placeholder: "https://twitter.com/McGillNLP"
    validations:
      required: false

  - type: input
    id: demo
    attributes:
      label: Demo
      description: Link to a demo showcasing the paper.
      placeholder: "https://project-demo.com"
    validations:
      required: false

  - type: "input"
    id: thumbnail
    attributes:
      label: "Thumbnail"
      description: |
        Path or URL to an image (such as a figure). If it's an URL, it will be resized, convert to JPG and saved to `/assets/images/papers`. Please use an image with aspect ratio of 4:3.

        Tip: Please see FAQ if you want to upload an image to GitHub.
      
      placeholder: "/assets/images/papers/project-thumbnail.jpg"
    validations:
      required: false

  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: |
        The abstract of the paper. Please do not use `###`.

        Note: If you select "Update publication", this field is completely ignored.
      placeholder: |
        Our paper introduces recursion. We show it achieves state-of-the-art results on MNIST. We  believe it is all you need because...
    validations:
      required: false
